# Generated by Django 6.0 on 2026-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
