# Generated by Django 6.0 on 2026-04-11 12:11

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_orderitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='order',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='address',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='deal_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='life',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='authentic_rating',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='chat_response_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='days_return',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shipping_on_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='warranty',
        ),
        migrations.AddField(
            model_name='order',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.CharField(choices=[('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='3', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='+1234567890', max_length=20),
        ),
        migrations.DeleteModel(
            name='CartOrderItem',
        ),
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
    ]
